### ISSUE TITLE
The required native library 'phonon' was not found

### ISSUE THREAD

**Issue by ertugrulcetin** [riccardobl/FPSDEMO-jMonkeyEngine#4]
Hi!
This project looks really cool! Thank you for making it. I'm having some problems to run the project and get some errors;

`java.lang.UnsatisfiedLinkError: The required native library 'phonon' was not found in the classpath via 'native/OSX/x86_64/libphonon.dylib'. Error message: no phonon in java.library.path: [/Users/ertu/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]`

I'm using MacBook Pro (10.14.6) and JDK 14.0.1 (also tried 8 and 11 as well, no luck)

Any idea how to run on OS X?

**Comment by riccardobl** [comment]
Hello, sorry for the late reply.
The version 1.0.0 was not compatible with mac because the jmePhonon native library was not built for mac on travis. 
I updated and moved the build script to github actions and released a new 1.0.1 version with mac natives, you can try it and see if it works as expected:  https://github.com/riccardobl/FPSDEMO-jMonkeyEngine/releases/tag/1.0.1

**Comment by ertugrulcetin** [comment]
@riccardobl thanks for the update!
